# Site
repository: tejaswini4354/modern-resume-theme
# favicon: images/favicon.ico (optional)

# Content configuration version
version: 2

# Personal info
name: Sai Tejaswini Junnuri
title: AI Enthusiast | Data Scientist
email: saitejaswinijunnuri@gmail.com
phone: 857-961-7174
website: https://github.com/tejaswini4354
# website_title: GitHub Profile

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ""
github_username: tejaswini4354
stackoverflow_username: ""
dribbble_username: ""
facebook_username: ""
flickr_username: ""
instagram_username: ""
linkedin_username: junnuri-sai-tejaswini-849748147
xing_username: ""
pinterest_username: ""
youtube_username: ""
orcid_username: ""
googlescholar_username: ""

# Additional icon links
additional_links:
  - title: Credly Badge
    icon: fab fa-credly
    url: https://www.credly.com/badges/683f0593-883a-4062-9684-0280762b1094/linked_in_profile
  - title: Ovarian Cancer Classification Project
    icon: fab fa-github
    url: https://github.com/tejaswini4354/OvarianCancerClassification
  - title: LLM Movie Recommender Project
    icon: fab fa-github
    url: https://github.com/Exorust/LLM-movie-recommender

# Google Analytics and Tag Manager
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_profile_image: images/profile.jpg
about_content: |
  I am an AI enthusiast and graduate student with over five years of experience in data science, machine learning, and AI development. My expertise spans natural language processing, computer vision, and predictive analytics, and I have successfully delivered impactful solutions for businesses across various industries. From deploying machine learning models to driving innovation with large language models, I thrive in dynamic environments that challenge my problem-solving abilities. My passion lies in using AI to enhance decision-making processes, develop innovative tools, and deliver meaningful insights. I am eager to contribute to cutting-edge projects that push the boundaries of technology.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: Ovarian Cancer Classification
        link: https://github.com/tejaswini4354/OvarianCancerClassification
        link_text: View Project
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/tejaswini4354/OvarianCancerClassification
        description: |
          Developed and optimized a ResNet 101 model for ovarian cancer subtype classification using histopathology images from over 20 medical centers. Implemented advanced data augmentation techniques like CutMix and MixUp to address class imbalance and enhance model generalizability.

      - layout: left
        border: weak
        title: LLM Movie Recommender
        link: https://github.com/Exorust/LLM-movie-recommender
        link_text: View Project
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/Exorust/LLM-movie-recommender
        description: |
          Fine-tuned Mistral LLM for personalized movie recommendations on the MovieLens dataset. Enhanced prediction accuracy by integrating binary ratings and genre information to significantly improve personalized recommendation quality.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: Boom
        sub_title: AI Developer Intern
        caption: May 2024 – Aug 2024
        description: |
          - Developed and deployed a valuation tool that extracts key financial data and business descriptions from documents, providing comprehensive valuations by identifying comparable transactions for similar businesses.
          - Created a buyer search platform that matches businesses to buyers based on detailed profiles, enhancing business transactions.
        
      - layout: right
        title: Merilytics
        sub_title: Lead Data Scientist
        caption: Oct 2022 – Jul 2023
        description: |
          - Led data procurement in Azure for a $200M+ legal firm, combining UiPath (RPA) with ML models to enhance data quality.
          - Developed tools for sentiment analysis using BERT and TensorFlow to gain client insights and reduce customer default rates by 9% for a finance firm.
          - Spearheaded end-to-end MLOps management on Azure for multiple machine learning models.

      - layout: right
        title: Merilytics
        sub_title: Associate Data Scientist
        caption: Apr 2021 – Sep 2022
        description: |
          - Implemented Markov Chain-based marketing channel attribution, resulting in a 7% reduction in cost per conversion.
          - Utilized Mask R-CNN to assess space utilization efficiency by analyzing images for a trucking company.
          - Developed and deployed a versatile time-series forecasting tool in AWS featuring data handling, outlier detection, and hierarchical forecasting.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Boston University
        sub_title: MS in Artificial Intelligence
        caption: Sep 2023 – Dec 2024
        description: |
          Relevant coursework: Natural Language Processing, Artificial Intelligence, Image and Video Computing, Reinforcement Learning, Deep Learning, Machine Learning.
          
      - layout: top-right
        title: Birla Institute of Technology and Sciences, Hyderabad
        sub_title: B.E.(Hons.) in Computer Science
        caption: Aug 2015 – May 2019
        description: |
          Relevant coursework: Data Structures, Algorithms, Machine Learning, and Deep Learning.

  - title: A Little More About Me
    layout: text
    content: |
      I am passionate about AI innovations and enjoy solving complex problems. In my spare time, I like to explore new AI techniques, contribute to open-source projects, and continuously learn about advancements in machine learning and AI-driven technology.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
